version: '3.8'

volumes:
  mariadb-volume:
  wordpress-volume:

networks:
  wp-network:

services:
  nginx:
    container_name: nginx
    build:
      context:  ./requirements/nginx
      args:
        - WP_SITE=${WP_SITE}
    volumes:
      - wordpress-volume:/var/www/${WP_SITE}
    networks:
      - wp-network
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build:
      context:  ./requirements/mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - wp-network
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_ROOT=${MARIADB_ROOT}
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
      - WP_DB=${WP_DB}
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build:
      context:  ./requirements/wordpress
      args:
        - WP_DIR=${WP_DIR}
    volumes:
      - wordpress-volume:/var/www/${WP_SITE}
    networks:
      - wp-network
    depends_on:
      - nginx
    restart: unless-stopped
