version: '3.8'

volumes:
  mariadb-volume:
  wordpress-volume:

networks:
  wp-network:

services:
  nginx:
    container_name: nginx
    build:
      context:  ./requirements/nginx
      args:
        - WP_SITE=${WP_SITE}
    volumes:
      - wordpress-volume:/var/www/${WP_SITE}
    networks:
      - wp-network
    ports:
      - "443:443"
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    environment:
      - WP_DB=${WP_DB}
      - MARIADB_ROOT=${MARIADB_ROOT}
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
    container_name: MariaDB
    build:
      context:  ./requirements/mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - wp-network
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build:
      context:  ./requirements/wordpress
      args:
        # SITE
        - WP_URL=${WP_URL}
        - WP_DB=${WP_DB}
        - WP_SITE=${WP_SITE}
        - WP_SITE_TITLE=${WP_SITE_TITLE}
        # USERS
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PWD=${WP_ADMIN_PWD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_USER=${WP_USER}
        - WP_USER_PWD=${WP_USER_PWD}
        - WP_USER_EMAIL=${WP_USER_EMAIL}
        # DATABASE ARGS
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_USER_PWD=${MARIADB_USER_PWD}
        - MARIADB_HOSTNAME=${MARIADB_HOSTNAME}
    volumes:
    - wordpress-volume:/var/www/${WP_SITE}
    networks:
      - wp-network
    depends_on:
      - mariadb
      - nginx
    restart: unless-stopped
