version: '3.8'

volumes:
  mariadb-volume:
  wordpress-volume:

networks:
  wp-network:

services:
  nginx:
    container_name: nginx
    build:
      context:  ./requirements/nginx
      args:
        - WP_SITE=${WP_SITE}
    volumes:
      - wordpress-volume:/var/www/${WP_SITE}
    networks:
      - wp-network
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build:
      context:  ./requirements/mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - wp-network
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build:
      context:  ./requirements/wordpress
      args:
        - WP_DIR=${WP_DIR}
    volumes:
      - wordpress-volume:/var/www/${WP_SITE}
    networks:
      - wp-network
    depends_on:
      - nginx
    restart: unless-stopped