version: '3'

volumes:
  mariadb-volume:
  wordpress-volume:

networks:
  nginx-network:
  mariadb-network:
  wordpress-network:

services:
  nginx:
    container_name: nginx
    build:
      context:  ./requirements/nginx
    volumes:
      - wordpress-volume:/var/www/${WP_SITE}
    networks:
      - nginx-network
    ports:
      - "443:443"
    #restart: unless-stopped
  mariadb:
    container_name: MariaDB
    build:
      context:  ./requirements/mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - mariadb-network
    environment:
      - MARIADB_ROOT=${MARIADB_ROOT}
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
    #restart: unless-stopped
  wordpress:
    container_name: wordpress
    build:
      context:  ./requirements/wordpress
      args:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
      - WP_URL=${WP_URL}
      - WP_DB=${WP_DB}
      - WP_SITE=sshakya.42.fr
      - WP_SITE_TITLE=${WP_SITE_TITLE}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    networks:
      - wordpress-network
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PWD=${MARIADB_USER_PWD}
      - WP_URL=${WP_URL}
      - WP_DB=${WP_DB}
      - WP_SITE=${WP_SITE}
      - WP_SITE_TITLE=${WP_SITE_TITLE}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    #restart: unless-stopped