DELETE FROM	mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
ALTER USER mysql@localhost IDENTIFIED VIA mysql_native_password;
SET PASSWORD FOR 'mysql'@'localhost' = PASSWORD('db_root_pwd');
CREATE DATABASE wp_db;
CREATE USER 'wp_user'@'%' IDENTIFIED by 'wp_user_pwd';
GRANT ALL PRIVILEGES ON wp_db.* TO wp_user@'%';
FLUSH PRIVILEGES;
